spring:
  application:
    name: api-gateway

  profiles:
    active: local

cloudflow:
  web:
    correlation-id:
      enabled: true
    request-logging:
      enabled: true
    exclude-paths:
      - /actuator/**
      - /swagger-ui/**
      - /v3/api-docs/**